name: Publish Crypto Analysis

on:
  # Runs on a daily schedule at 6 AM UTC, plus manual triggers
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the analysis script
      # Use your GitHub Secret for COINMARKETCAP_API_KEY
      env:
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      run: |
        python scripts/analysis.py

    - name: Copy output.json to docs/
      # This step copies the newly generated "scripts/output.json"
      # into "docs/output.json", so GH Pages can serve it.
      run: |
        cp scripts/output.json docs/output.json

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/output.json
        git commit -m "Update output.json [skip ci]" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin HEAD:${{ github.ref }}
